version: '3.8'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api:8000
      - HOST=0.0.0.0
      - PORT=3000
    command: npm run dev -- --host 0.0.0.0 --port 3000